version: '3.4'

services:
  spoopifyapi:
    image: spoopifyapi
    build:
      context: api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
